version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/pipo02mix/go-exercises

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: cd gigasecond
      - run: go get -v -t -d ./...
      - run: go test -v ./...

      - run: cd bob
      - run: go get -v -t -d ./...
      - run: go test -v ./...

